### ISSUE TITLE
How to write modules inside sass partials?

### ISSUE THREAD

**Issue by tushararora** [adamsilver/maintainablecss.com-jekyll#61]
Hi Adam.
Just read maintainablecss.com. Great stuff!

In modules chapter you presented an example of buttons - 

```
.basket-removeButton,
.another-loginButton,
.another-deleteButton {
  background-color: green;
  padding: 10px;
  color: #fff;
}
```

Now let's say I have multiple partials for auth, basket and orderSummary. Where should I put this css? Should I put this in the global module and then extend it to respective partials for other properties such as float, margin or width etc.? Because if I put this code in all the partials (depending on respective classes) it would mean code repetition. What's the better way according to you? Please help.

**Comment by hvab** [comment]
You can make module `button` with visual styles, and positioning set in mixes with parents modules. For example:

```html
<div class="auth">
  <button class="button auth-button">Auth</button>
</div>

<div class="basket">
  <button class="button basket-button">Order</button>
</div>
```
and styles:
```css
.button {
  background-color: green;
  padding: 10px;
  color: #fff;
}

.auth-button {
  margin-top: 1rem;
}

.basket-button {
  float: right;
}
```
